# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ibFJlkukuaYfaTuBvyjSzjmLyFFZtcBx
"""

for n in range(1,6):
  print('ola mundo')

lista =[1,3,6,89,78,15,56]
for n in lista:
#    print(n)

 for n in range(0,200):
    print(n)
for n in range (0,22,2):
   print(n)

for n in range(0,51,5):

  print(n)


usuario = input ('Digite seu nome')
print('Seja bem vindo,',usuario,)   ok


for n in range(1,11,2):
   print(n)
soma = sum(range(1,11,2))
   print(soma)