# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I6icFaFv5ZqT2Ycp7ceMbmd7pXiLWVF6
"""

# #SNAKE CASE
# #PALAVRAS COMPOSTAS
# #DECLARAÇÕES SEMÂNTICAS

# nome_do_usuario = input("Digite seu nome:")
# print(nome_do_usuario)

#concatenar (,) - juntar uma variável com um número
numero1 = 'r'
numero2 = 20
print(numero1,numero2)

#pedir para o usuário digitar o nome a idade e a cidade e depois concatenar tudo
# name = input ('Digite seu nome')
# age = input ('Digite sua idade')
# city = input ('Digite sua cidade')

# print('O nome do usuário é,', name, 'Sua idade é,', age, 'Ele mora na cidade:', city )

estado_civil = input ('Digite seu estado civil')
print('O usuário é,',estado_civil,)

dinheiro_real = 1.25 #REAIS
boleano = True or False #BOLEANOS
char = 'Text' #STRING OU CARACTERES
inteiro = 2 #INTEIROS
print(dinheiro_real, boleano, char, inteiro)



numero1 = 25
numero2 = 60
print(numero1+numero2)

numero1 = int(input('digite um número') )
numero2 = int(input('digite mais um número'))
print(numero1+numero2)

nome_do_usuario = input ('Digite seu nome')
print('O seu nome é,',nome_do_usuario,)



cumprimento = input ('Seja bem vindo')
print('Seja bem vindo,',cumprimento,)

n1 = int(input('Digite um numero'))
n2 = int(input('Digite outro numero'))
print(n1*n2)

senha_correta = '123456'
senha_digitada = input('Digete uma senha')

if senha_digitada == senha_correta:
  print('Acesso autorizado')
else:
  print('Acesso negado')

print('Acesso ao show')
idade = int(input('Digete sua idade->'))
if idade >= 18:
       print('Acesso liberado')
else:
     print('Acesso negado')

rua = "rua 11"
if rua != 'rua10':
  print('A festa é na rua 10')


print('Vacina para pessoas com 18anos')
idade = 18
if idade != 18:
  print('Não precisa tomar a vacina')
else:
    print('Precisa se vacinar')


n1 = int(input('Digite um número->'))
n2= int(input('Digite um número->'))
if n1 > n2:
  print('O primeiro é maior')
else:
  print('o seguno é maior')